# Generated by Django 2.2.5 on 2019-11-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('like_images', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.IntegerField()),
                ('total_likes', models.IntegerField(default=0)),
                ('tags', models.CharField(default='', max_length=200)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(default='', upload_to='img')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emoji.User')),
            ],
        ),
    ]
