# Generated by Django 2.2.6 on 2019-11-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='classification',
            field=models.CharField(default='', max_length=200),
        ),
    ]
