# Generated by Django 2.2.6 on 2019-11-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0002_auto_20191104_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
