# Generated by Django 2.2.6 on 2019-11-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0003_auto_20191104_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
