# Generated by Django 2.2.6 on 2019-11-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0006_auto_20191105_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
