# Generated by Django 2.2.6 on 2019-11-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0008_auto_20191105_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=20)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(to='emoji.Tag'),
        ),
    ]
