# Generated by Django 2.2.6 on 2019-11-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0010_auto_20191116_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
