# Generated by Django 2.2.6 on 2019-11-16 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0011_auto_20191116_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image2tag',
            old_name='tags',
            new_name='tag',
        ),
    ]
