# Generated by Django 2.2.6 on 2019-11-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0012_auto_20191116_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_thumbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.CharField(default='', max_length=5000000),
        ),
    ]
