# Generated by Django 2.2.6 on 2019-11-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0013_auto_20191116_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='private',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='portrait',
            field=models.CharField(default='', max_length=5000000),
        ),
        migrations.AddField(
            model_name='user',
            name='private',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(default='', max_length=100),
        ),
    ]
