# Generated by Django 2.2.6 on 2019-11-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0015_auto_20191126_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.IntegerField(default=0),
        ),
    ]
